$ ->
  $("#works-grid").gridSlider
    responsive:true,
    numCols:3,
    numRows:2,
    # minRows:2,
    slideWidth:300,
    slideHeight:200,
    slideBorder:5,
    slideMargin:10,	
    padding:10,
    # panelEffect:'coverDown',
    # captionEffect:'slide',
    captionAlign: 'bottom',
    captionPosition: 'outside',
    # captionHeight: 50,
    # captionWidth:100,
    # captionHeight:'auto',
    # hoverEffect:'zoomIn',
    # keyboard:true,			
    # mousewheel:true,
    # hoverBox: {
    # 	width:250,
    # 	height:'auto',
    # 	delay:1000,
    # 	toggle:true
    # }
    
    # numCols:          3,
    # numRows:          2,
    # slideWidth:       300,
    # slideHeight:      200,
    # slideBorder:50,
    # slideMargin:10,	
    # padding:10,
    # # slideBorder:      10,
    # imagePosition:    'fill',
    # captionAlign:     'bottom',
    # # captionPosition:  'outside',
    # captionHeight:    50
